# Generated by Django 5.1.4 on 2025-01-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('table', 'booking_date', 'booking_time')},
        ),
    ]
